customhost = "database-1.cmibo48vwduh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "foomengwen_employee"
custombucket = "foomengwen-employee"
customregion = "us-east-1"
